version: '3'
services:
  frontend:
    image: myapp/frontend-test:latest
    links:
      - backend
    ports:
      - "12345:80"
    environment:
      - BACKEND_SERVICE=http://backend
    container_name: frontend
  backend:
    image: nginx:1.13.3
    volumes:
      - ./backend-app/nginx.conf:/etc/nginx/nginx.conf
      - ./backend-app/secret.key:/opt/app/secret.key
    container_name: backend
