apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: demo
data:
  nginx.conf: |
    worker_processes 4;
    events {}

    http {
      access_log  off;
      error_log   off;

      server {
        listen  80;

        location /secret/ {
          index secret.key;
          alias /opt/app/;
        }

      }
    }

